import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { v7 as uuid } from 'uuid';
import { Wallet } from '../../shared/entities/wallet.entity';
import { WalletResponseDTO } from './dto/wallet-response.dto';

@Injectable()
export class WalletService {
  constructor(
    @InjectRepository(Wallet)
    private walletRepository: Repository<Wallet>,
  ) {}

  /**
   * Every user gets exactly one wallet, created on first access rather than at registration —
   * this keeps the wallet module fully decoupled from AuthService.register. `orIgnore()` makes
   * concurrent first-accesses (e.g. two parallel requests right after signup) safe: at most one
   * insert wins, the other is a no-op, and both paths re-select the same row afterwards.
   */
  async getOrCreateWallet(userId: string): Promise<Wallet> {
    const existing = await this.walletRepository.findOne({ where: { userId } });
    if (existing) {
      return existing;
    }

    // `Wallet.id` is a plain `@PrimaryColumn` whose default is generated by the entity class's
    // field initializer (`id = uuid()`), which only runs when a `Wallet` instance is constructed.
    // The query builder's `.values()` takes a plain object, not an entity instance, so the id must
    // be generated here explicitly — otherwise it's left NULL and the insert violates the PK.
    await this.walletRepository
      .createQueryBuilder()
      .insert()
      .into(Wallet)
      .values({ id: uuid(), userId })
      .orIgnore()
      .execute();

    return this.walletRepository.findOneByOrFail({ userId });
  }

  async getWalletBalance(userId: string): Promise<WalletResponseDTO> {
    const wallet = await this.getOrCreateWallet(userId);
    return this.toWalletResponse(wallet);
  }

  private toWalletResponse(wallet: Wallet): WalletResponseDTO {
    return {
      id: wallet.id,
      balance: wallet.balance.toFixed(4),
      currency: wallet.currency,
      createdAt: wallet.createdAt,
      updatedAt: wallet.updatedAt,
    };
  }
}
