import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import Decimal from 'decimal.js';
import { DataSource, In, QueryFailedError, Repository } from 'typeorm';
import { v7 as uuid } from 'uuid';
import { LedgerDirection, TransactionStatus, TransactionType } from '../../shared/enums/wallet.enum';
import { LedgerEntry } from '../../shared/entities/ledger-entry.entity';
import { Transaction } from '../../shared/entities/transaction.entity';
import { Wallet } from '../../shared/entities/wallet.entity';
import { UsersService } from '../users/users.service';
import { DepositDTO } from './dto/deposit.dto';
import { TransactionResponseDTO } from './dto/transaction-response.dto';
import { TransferDTO } from './dto/transfer.dto';
import { WalletResponseDTO } from './dto/wallet-response.dto';
import { RecipientNotFoundException } from './exceptions/recipient-not-found.exception';
import { TransactionAlreadyReversedException } from './exceptions/transaction-already-reversed.exception';
import { WalletNotFoundException } from './exceptions/wallet-not-found.exception';
import {
  assertNotSelfTransfer,
  assertReversible,
  assertSufficientBalance,
  computeReversalWalletIds,
} from './wallet-rules';

@Injectable()
export class WalletService {
  constructor(
    @InjectRepository(Wallet)
    private walletRepository: Repository<Wallet>,
    @InjectRepository(Transaction)
    private transactionRepository: Repository<Transaction>,
    @InjectRepository(LedgerEntry)
    private ledgerEntryRepository: Repository<LedgerEntry>,
    private usersService: UsersService,
    private dataSource: DataSource,
  ) {}

  /**
   * Every user gets exactly one wallet, created on first access rather than at registration —
   * this keeps the wallet module fully decoupled from AuthService.register. `orIgnore()` makes
   * concurrent first-accesses (e.g. two parallel requests right after signup) safe: at most one
   * insert wins, the other is a no-op, and both paths re-select the same row afterwards.
   */
  async getOrCreateWallet(userId: string): Promise<Wallet> {
    const existing = await this.walletRepository.findOne({ where: { userId } });
    if (existing) {
      return existing;
    }

    // `Wallet.id` is a plain `@PrimaryColumn` whose default is generated by the entity class's
    // field initializer (`id = uuid()`), which only runs when a `Wallet` instance is constructed.
    // The query builder's `.values()` takes a plain object, not an entity instance, so the id must
    // be generated here explicitly — otherwise it's left NULL and the insert violates the PK.
    await this.walletRepository
      .createQueryBuilder()
      .insert()
      .into(Wallet)
      .values({ id: uuid(), userId })
      .orIgnore()
      .execute();

    return this.walletRepository.findOneByOrFail({ userId });
  }

  async getWalletBalance(userId: string): Promise<WalletResponseDTO> {
    const wallet = await this.getOrCreateWallet(userId);
    return this.toWalletResponse(wallet);
  }

  async deposit(userId: string, dto: DepositDTO): Promise<TransactionResponseDTO> {
    const existing = await this.findIdempotentTransaction(userId, dto.idempotencyKey);
    if (existing) {
      return this.toTransactionResponse(existing);
    }

    await this.getOrCreateWallet(userId);
    const amount = new Decimal(dto.amount);

    try {
      return await this.dataSource.transaction(async (manager) => {
        const walletRepository = manager.getRepository(Wallet);
        const wallet = await walletRepository.findOne({
          where: { userId },
          lock: { mode: 'pessimistic_write' },
        });
        if (!wallet) {
          throw new WalletNotFoundException();
        }

        wallet.balance = wallet.balance.plus(amount);
        await walletRepository.save(wallet);

        const transaction = manager.getRepository(Transaction).create({
          type: TransactionType.DEPOSIT,
          amount,
          toWalletId: wallet.id,
          requestedByUserId: userId,
          idempotencyKey: dto.idempotencyKey ?? null,
        });
        await manager.getRepository(Transaction).save(transaction);

        const ledgerEntry = manager.getRepository(LedgerEntry).create({
          transactionId: transaction.id,
          walletId: wallet.id,
          direction: LedgerDirection.CREDIT,
          amount,
          balanceAfter: wallet.balance,
        });
        await manager.getRepository(LedgerEntry).save(ledgerEntry);

        return this.toTransactionResponse(transaction);
      });
    } catch (error) {
      if (dto.idempotencyKey && this.isIdempotencyKeyConflict(error)) {
        const replay = await this.findIdempotentTransaction(userId, dto.idempotencyKey);
        if (replay) {
          return this.toTransactionResponse(replay);
        }
      }
      throw error;
    }
  }

  async transfer(userId: string, dto: TransferDTO): Promise<TransactionResponseDTO> {
    const existing = await this.findIdempotentTransaction(userId, dto.idempotencyKey);
    if (existing) {
      return this.toTransactionResponse(existing);
    }

    const recipient = await this.usersService.findByEmail(dto.toEmail);
    if (!recipient) {
      throw new RecipientNotFoundException();
    }
    assertNotSelfTransfer(userId, recipient.id);

    await this.getOrCreateWallet(userId);
    await this.getOrCreateWallet(recipient.id);
    const amount = new Decimal(dto.amount);

    try {
      return await this.dataSource.transaction(async (manager) => {
        const walletRepository = manager.getRepository(Wallet);
        // Lock in a deterministic order (sorted user id) regardless of who is sender/receiver,
        // so two transfers between the same pair of wallets in opposite directions can never
        // deadlock waiting on each other's row lock.
        const [firstUserId, secondUserId] = [userId, recipient.id].sort();
        const firstWallet = await walletRepository.findOne({
          where: { userId: firstUserId },
          lock: { mode: 'pessimistic_write' },
        });
        const secondWallet = await walletRepository.findOne({
          where: { userId: secondUserId },
          lock: { mode: 'pessimistic_write' },
        });
        if (!firstWallet || !secondWallet) {
          throw new WalletNotFoundException();
        }

        const source = firstWallet.userId === userId ? firstWallet : secondWallet;
        const destination = firstWallet.userId === userId ? secondWallet : firstWallet;

        assertSufficientBalance(source.balance, amount);

        source.balance = source.balance.minus(amount);
        destination.balance = destination.balance.plus(amount);
        await walletRepository.save([source, destination]);

        const transaction = manager.getRepository(Transaction).create({
          type: TransactionType.TRANSFER,
          amount,
          fromWalletId: source.id,
          toWalletId: destination.id,
          requestedByUserId: userId,
          idempotencyKey: dto.idempotencyKey ?? null,
        });
        await manager.getRepository(Transaction).save(transaction);

        await manager.getRepository(LedgerEntry).save([
          manager.getRepository(LedgerEntry).create({
            transactionId: transaction.id,
            walletId: source.id,
            direction: LedgerDirection.DEBIT,
            amount,
            balanceAfter: source.balance,
          }),
          manager.getRepository(LedgerEntry).create({
            transactionId: transaction.id,
            walletId: destination.id,
            direction: LedgerDirection.CREDIT,
            amount,
            balanceAfter: destination.balance,
          }),
        ]);

        return this.toTransactionResponse(transaction);
      });
    } catch (error) {
      if (dto.idempotencyKey && this.isIdempotencyKeyConflict(error)) {
        const replay = await this.findIdempotentTransaction(userId, dto.idempotencyKey);
        if (replay) {
          return this.toTransactionResponse(replay);
        }
      }
      throw error;
    }
  }

  async reverse(adminUserId: string, transactionId: string): Promise<TransactionResponseDTO> {
    const original = await this.transactionRepository.findOne({ where: { id: transactionId } });
    if (!original) {
      throw new NotFoundException('Transação não encontrada');
    }
    assertReversible(original);

    const walletIds = [original.fromWalletId, original.toWalletId].filter(
      (id): id is string => id !== null,
    );

    // reverse() can touch the same two wallets a concurrent transfer() is touching, so it must
    // lock them in the same order transfer() does — sorted by the owning user's id, not by the
    // wallet's own id — or the two methods could deadlock against each other. We only have wallet
    // ids here (from the original transaction), so we look up each wallet's userId first,
    // unlocked, purely to compute a consistent lock order before entering the transaction.
    const walletsForOrdering = await this.walletRepository.find({ where: { id: In(walletIds) } });
    const userIdByWalletId = new Map(walletsForOrdering.map((wallet) => [wallet.id, wallet.userId]));
    const sortedWalletIds = [...walletIds].sort((a, b) => {
      const userIdA = userIdByWalletId.get(a) ?? '';
      const userIdB = userIdByWalletId.get(b) ?? '';
      return userIdA < userIdB ? -1 : userIdA > userIdB ? 1 : 0;
    });

    try {
      return await this.dataSource.transaction(async (manager) => {
        const transactionRepository = manager.getRepository(Transaction);
        const walletRepository = manager.getRepository(Wallet);
        const ledgerRepository = manager.getRepository(LedgerEntry);

        const lockedOriginal = await transactionRepository.findOne({ where: { id: transactionId } });
        if (!lockedOriginal) {
          throw new NotFoundException('Transação não encontrada');
        }
        assertReversible(lockedOriginal);

        const wallets = new Map<string, Wallet>();
        for (const id of sortedWalletIds) {
          const wallet = await walletRepository.findOne({
            where: { id },
            lock: { mode: 'pessimistic_write' },
          });
          if (!wallet) {
            throw new WalletNotFoundException();
          }
          wallets.set(id, wallet);
        }

        const { fromWalletId, toWalletId } = computeReversalWalletIds(lockedOriginal);

        // fromWalletId here is whoever received in the original transaction — always set for a
        // completed deposit or transfer — and gets debited back. No balance-sufficiency check:
        // reversing on top of money the recipient already spent elsewhere is exactly the
        // "negative balance for some reason" case the spec calls out, and it's deliberate.
        const debitedWallet = wallets.get(fromWalletId as string)!;
        debitedWallet.balance = debitedWallet.balance.minus(lockedOriginal.amount);
        const ledgerEntries = [
          ledgerRepository.create({
            walletId: debitedWallet.id,
            direction: LedgerDirection.DEBIT,
            amount: lockedOriginal.amount,
            balanceAfter: debitedWallet.balance,
          }),
        ];

        if (toWalletId) {
          const creditedWallet = wallets.get(toWalletId)!;
          creditedWallet.balance = creditedWallet.balance.plus(lockedOriginal.amount);
          ledgerEntries.push(
            ledgerRepository.create({
              walletId: creditedWallet.id,
              direction: LedgerDirection.CREDIT,
              amount: lockedOriginal.amount,
              balanceAfter: creditedWallet.balance,
            }),
          );
        }

        await walletRepository.save([...wallets.values()]);

        const reversalTransaction = transactionRepository.create({
          type: TransactionType.REVERSAL,
          amount: lockedOriginal.amount,
          fromWalletId,
          toWalletId,
          reversalOfId: lockedOriginal.id,
          requestedByUserId: adminUserId,
        });
        await transactionRepository.save(reversalTransaction);

        for (const entry of ledgerEntries) {
          entry.transactionId = reversalTransaction.id;
        }
        await ledgerRepository.save(ledgerEntries);

        lockedOriginal.status = TransactionStatus.REVERSED;
        await transactionRepository.save(lockedOriginal);

        return this.toTransactionResponse(reversalTransaction);
      });
    } catch (error) {
      if (this.isReversalConflict(error)) {
        throw new TransactionAlreadyReversedException();
      }
      throw error;
    }
  }

  private async findIdempotentTransaction(
    requestedByUserId: string,
    idempotencyKey?: string,
  ): Promise<Transaction | null> {
    if (!idempotencyKey) {
      return null;
    }
    return this.transactionRepository.findOne({ where: { requestedByUserId, idempotencyKey } });
  }

  private isIdempotencyKeyConflict(error: unknown): boolean {
    if (!(error instanceof QueryFailedError)) {
      return false;
    }
    // TypeORM's default naming strategy hashes the partial unique index name (e.g.
    // "IDX_06f35ca5180e2f830b5f48ee43"), so it never appears in `error.message`. The Postgres
    // driver does copy `code` and `detail` onto the QueryFailedError instance though, and
    // `detail` spells out the offending columns (e.g. "Key (requested_by_user_id,
    // idempotency_key)=(...) already exists."), which is what we key off of to keep this
    // narrowly scoped to the idempotency constraint rather than any other unique violation.
    const driverError = error as QueryFailedError & { code?: string; detail?: string };
    return driverError.code === '23505' && !!driverError.detail?.includes('idempotency_key');
  }

  private isReversalConflict(error: unknown): boolean {
    if (!(error instanceof QueryFailedError)) {
      return false;
    }
    // Task 2's partial unique index on Transaction.reversalOfId (`WHERE reversal_of_id IS NOT
    // NULL`) is the DB-level backstop against double-reversal, in case two concurrent admin
    // reversal requests for the same transaction both pass the in-transaction status check
    // before either commits.
    const driverError = error as QueryFailedError & { code?: string; detail?: string };
    return driverError.code === '23505' && !!driverError.detail?.includes('reversal_of_id');
  }

  private toWalletResponse(wallet: Wallet): WalletResponseDTO {
    return {
      id: wallet.id,
      balance: wallet.balance.toFixed(4),
      currency: wallet.currency,
      createdAt: wallet.createdAt,
      updatedAt: wallet.updatedAt,
    };
  }

  private toTransactionResponse(transaction: Transaction): TransactionResponseDTO {
    return {
      id: transaction.id,
      type: transaction.type,
      status: transaction.status,
      amount: transaction.amount.toFixed(4),
      fromWalletId: transaction.fromWalletId,
      toWalletId: transaction.toWalletId,
      reversalOfId: transaction.reversalOfId,
      requestedByUserId: transaction.requestedByUserId,
      idempotencyKey: transaction.idempotencyKey,
      createdAt: transaction.createdAt,
    };
  }
}
